//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charges_archiveClarity
    {
        public int id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string claim_type { get; set; }
        public string description { get; set; }
        public double total_claim_amount { get; set; }
        public double eligible_amount { get; set; }
        public double approved_amount { get; set; }
        public double ineligible_amount { get; set; }
        public double pended_amount { get; set; }
        public double denied_amount { get; set; }
        public string denied_reason { get; set; }
        public string claim_number { get; set; }
        public string scc_mcc { get; set; }
        public int employee_id { get; set; }
        public Nullable<int> loan_id { get; set; }
        public string company_identifier { get; set; }
    }
}
