//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronLog
    {
        public int id { get; set; }
        public System.DateTime cron_timestamp { get; set; }
        public string cron_type { get; set; }
        public string cron_log { get; set; }
    }
}
