//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomReportSchedulesBU
    {
        public int id { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public int report_id { get; set; }
        public string recurrence { get; set; }
        public string start_date { get; set; }
    }
}
