//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeedLog()
        {
            this.feed_log_details = new HashSet<FeedLogDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime feed_timestamp { get; set; }
        public string feed_name { get; set; }
        public string feed_direction { get; set; }
        public string feed_location { get; set; }
        public bool successful { get; set; }
    
        public virtual OrganizationSettings organization_setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedLogDetail> feed_log_details { get; set; }
    }
}
