//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSA_error_log
    {
        public int Feed_ID { get; set; }
        public System.DateTime feed_timestamp { get; set; }
        public string feed_name { get; set; }
        public string feed_direction { get; set; }
        public string feed_location { get; set; }
        public int message_ID { get; set; }
        public string log_message { get; set; }
        public System.DateTime message_timestamp { get; set; }
    }
}
