//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationSettings()
        {
            this.feed_logs = new HashSet<FeedLog>();
            this.repayment_table = new HashSet<RepaymentTable>();
        }
    
        public int id { get; set; }
        public string deposits_feed { get; set; }
        public string demographics_feed { get; set; }
        public string alegeus_feed { get; set; }
        public bool withhold_entire_balance { get; set; }
    
        public virtual Organization organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedLog> feed_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepaymentTable> repayment_table { get; set; }
    }
}
