//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportEntity()
        {
            this.indentation_level = 0;
            this.section_delimiter = ",";
            this.format_option_fixed_width = 0;
            this.format_option_capitalize_entire_element = 0;
            this.format_option_remove_characters = 0;
            this.format_option_date = 0;
            this.format_option_currency = 0;
            this.collapsed = false;
            this.entity_options = new HashSet<EntityOption>();
            this.child_entities = new HashSet<ReportEntity>();
        }
    
        public int id { get; set; }
        public int indentation_level { get; set; }
        public string caption { get; set; }
        public string format { get; set; }
        public string literal_value { get; set; }
        public string option { get; set; }
        public string section_delimiter { get; set; }
        public string format_json { get; set; }
        public string map_json { get; set; }
        public int format_option_fixed_width { get; set; }
        public Nullable<int> format_option_fixed_width_val { get; set; }
        public int format_option_capitalize_entire_element { get; set; }
        public int format_option_remove_characters { get; set; }
        public string format_option_remove_characters_list { get; set; }
        public int format_option_date { get; set; }
        public string format_option_date_format { get; set; }
        public int format_option_currency { get; set; }
        public string format_option_currency_format { get; set; }
        public bool collapsed { get; set; }
    
        public virtual AvailableEntity available_entity { get; set; }
        public virtual Report report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityOption> entity_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportEntity> child_entities { get; set; }
        public virtual ReportEntity parent_entities { get; set; }
    }
}
