//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClarityContextContainer : DbContext
    {
        public ClarityContextContainer()
            : base("name=ClarityContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Demographic> Demographics { get; set; }
        public virtual DbSet<Charge> Charges { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<DashboardConfig> DashboardConfigs { get; set; }
        public virtual DbSet<OrganizationSettings> OrganizationSettings { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<CustomReportSchedule> CustomReportSchedules { get; set; }
        public virtual DbSet<ReportField> ReportFields { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<FeedLog> FeedLogs { get; set; }
        public virtual DbSet<RepaymentTable> RepaymentTables { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<AvailableEntity> AvailableEntities { get; set; }
        public virtual DbSet<AvailableEntityOption> AvailableEntityOptions { get; set; }
        public virtual DbSet<ReportEntity> ReportEntities { get; set; }
        public virtual DbSet<EntityOption> EntityOptions { get; set; }
        public virtual DbSet<ReportFieldChange> ReportFieldChanges { get; set; }
        public virtual DbSet<FeedLogDetail> FeedLogDetails { get; set; }
        public virtual DbSet<Report834Options> Report834Options { get; set; }
        public virtual DbSet<CronLog> CronLogs { get; set; }
        public virtual DbSet<Termination> Terminations { get; set; }
    }
}
