//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardConfig
    {
        public int id { get; set; }
        public string quadrant_1 { get; set; }
        public string quadrant_2 { get; set; }
        public string quadrant_3 { get; set; }
        public string quadrant_4 { get; set; }
    
        public virtual User user { get; set; }
    }
}
