//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityOption
    {
        public int id { get; set; }
        public string option_value { get; set; }
    
        public virtual ReportEntity report_entity { get; set; }
        public virtual AvailableEntityOption available_entity_option { get; set; }
    }
}
