//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportField
    {
        public int id { get; set; }
        public string name { get; set; }
        public string source { get; set; }
        public string format { get; set; }
        public string field_type { get; set; }
        public string calculation { get; set; }
        public int field_order { get; set; }
    
        public virtual Report report { get; set; }
        public virtual Field field { get; set; }
    }
}
