//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.is_report_builder = false;
            this.custom_report_schedules = new HashSet<CustomReportSchedule>();
            this.fields = new HashSet<ReportField>();
            this.report_entities = new HashSet<ReportEntity>();
            this.report_field_changes = new HashSet<ReportFieldChange>();
            this.terminations = new HashSet<Termination>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string grouping_field { get; set; }
        public bool show_totals { get; set; }
        public bool show_subtotals { get; set; }
        public string output_format { get; set; }
        public string delivery_type { get; set; }
        public string schedule_type { get; set; }
        public string delivery_email_address { get; set; }
        public string delivery_ftp_address { get; set; }
        public string delivery_ftp_username { get; set; }
        public string delivery_ftp_password { get; set; }
        public string delivery_ftp_port { get; set; }
        public string delivery_ftp_path { get; set; }
        public bool is_report_builder { get; set; }
        public string global_report_orgs { get; set; }
        public string header { get; set; }
        public string footer { get; set; }
        public string xml_file_path { get; set; }
        public string output_filename { get; set; }
    
        public virtual Organization organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomReportSchedule> custom_report_schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportField> fields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportEntity> report_entities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFieldChange> report_field_changes { get; set; }
        public virtual Report834Options report_834_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termination> terminations { get; set; }
    }
}
