//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clarity_HSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report834Options
    {
        public int id { get; set; }
        public string isa02 { get; set; }
        public string isa03 { get; set; }
        public string isa04 { get; set; }
        public string isa05 { get; set; }
        public string isa06 { get; set; }
        public string isa07 { get; set; }
        public string isa08 { get; set; }
        public string isa13 { get; set; }
        public string isa14 { get; set; }
        public string gs02 { get; set; }
        public string gs03 { get; set; }
        public string gs06 { get; set; }
        public string gs08 { get; set; }
        public string bgn02 { get; set; }
        public string bgn08 { get; set; }
        public string st02 { get; set; }
        public string dtp03 { get; set; }
        public string isa01 { get; set; }
        public string isa15 { get; set; }
        public string bgn06 { get; set; }
        public string ref02 { get; set; }
        public string dtp01 { get; set; }
        public string n102a { get; set; }
        public string n103a { get; set; }
        public string n104a { get; set; }
        public string n102b { get; set; }
        public string n103b { get; set; }
        public string n104b { get; set; }
        public string n102c { get; set; }
        public string n103c { get; set; }
        public string n104c { get; set; }
        public string dtp01b { get; set; }
        public string dtp03b { get; set; }
        public int include_qty_a { get; set; }
        public int include_qty_b { get; set; }
        public int include_qty_c { get; set; }
        public int include_n1_a { get; set; }
        public int include_n1_b { get; set; }
        public int include_n1_c { get; set; }
        public int include_dtp_a { get; set; }
        public int include_dtp_b { get; set; }
        public bool remove_line_breaks { get; set; }
        public bool remove_tildes { get; set; }
    
        public virtual Report report { get; set; }
    }
}
